### PR TITLE
Support for Gnome 44 

### PR DESCRIPTION
**Pull request by KljajicS**
Issue: #59  

Tested on Fedora 38 Gnome 44, Resolution: 5120x1440

### CODE REVIEW

**Comment by Simranpal** [comment]
Tested on Fedora 38, the icon disappears and app does not work after reboot.
Gnome 44, Resolution: 5120x1440

**Comment by sjoerdschouten** [comment]
Tested on Fedora 38 Gnome 44 on Xorg, Resolution: 3440x1440. 
Functionally gSnap seems to work fine. However, I do need to reinstall it after rebooting to get it up and running again but perhaps that just way install from source works?

**Comment by sjoerdschouten** [comment]
@KljajicS I see, I was about so to say something similar happens when switching from X to Wayland but that explains it :) Thanks

**Comment by Simranpal** [comment]
I added the shell version in metadata.json file (@ /.local/share/gnome-shell/extensions/gSnap@micahosborne)
and it seems to be working fine after each session now.

**Comment by jatozy** [comment]
Tested on Ubuntu 23.04, Gnome 44, Resolution 4096x2160.
It works.

**Comment by domferr** [comment]
Tested on Ubuntu 23.04, Gnome 44, both Wayland and Xorg, works great.

**Pull request merged**
