### PR TITLE
Add support for GNOME 46

### LINKED ISSUE #82: Update for gnome 46
Hey, thanks for the great extension!
Really happy so far, and I was very unhappy when I had to resort to the default snapping behaviour when i updated to gnome 46. Fortunately, I don't think anything broke (I have just changed the version number in the metadata, and everything works so far at least on my end).

### PR DESCRIPTION
**Pull request by gtirloni**
I haven't noticed any issues with GNOME 46 (Fedora 40 Beta).

Resolves #82

### CODE REVIEW

**Comment by perinm** [comment]
Bump! Will also test this upon release of Ubuntu 24.04, but this PR is probably already harmless

**Comment by KylerJohnsonDev** [comment]
I haven't come across any issues with this branch. Looks good to me, too.

**Comment by perinm** [comment]
LGTM too on Ubuntu 24.04 LTS!
image

**Comment by ShoQue92** [comment]
Using this change, I have executed the steps as mentioned in `DEVELOPING.md`, but it still seems to think its for GNOME 45. Am i missing something? Running Ubuntu 24.04.

image


image

**Comment by perinm** [comment]
Probably, here works normally. Did you paste the contents output of the
build in the extension folder?

**Comment by ShoQue92** [comment]
I asumed the build step would do that for me. I checked the extensions folder and saw files with a simmilar timestamp as in the ./dist folder of where i executed the build command.

Cleared the extensions folder and moved those files over to double check, same result.
Im new to building extensions, so bare with me.

**Comment by nittendev** [comment]
Running on fedora 40. Working great.
Also as an aside, this is the best extension ever. I can't live without it.

**Comment by perinm** [comment]
> I asumed the build step would do that for me. I checked the extensions folder and saw files with a simmilar timestamp as in the ./dist folder of where i executed the build command.
> 
> Cleared the extensions folder and moved those files over to double check, same result. Im new to building extensions, so bare with me.

@ShoQue92 
I just remembered couple things I did that might help you.
1. I deleted the content on the extension folder and replaced with dist ones.
2. I made sure the folder was called "gSnap@micahosborne" and was at ".local/share/gnome-shell/extensions/gSnap@micahosborne"
3. I searched for extensions in Ubuntu applications menu, opened and enabled extensions and gSnap extension.

**Review by meronz — APPROVED** [review]

**Comment by meronz** [comment]
Sorry for the delay. I merged the PR and I'll do some testing and push the release to EGO today.

**Comment by meronz** [comment]
> I asumed the build step would do that for me. I checked the extensions folder and saw files with a simmilar timestamp as in the ./dist folder of where i executed the build command.
> 
> Cleared the extensions folder and moved those files over to double check, same result. Im new to building extensions, so bare with me.

Sometimes it happens that the extension you build is "updated" with the version available on extensions.gnome.org. To avoid any unexpected update, in manifest.json set the version to something like 9999. This way the extension won't be replaces with the currently released version :)

**Pull request merged**
