### PR TITLE
Allow spanning of multiple zones by holding ALT key

### LINKED ISSUE #33: Feature Request: Allow windows to span multiple zones
I have multiple layouts that are refinements of each other (meaning that every
zone of one layout is a union of zones of the other layout). I would like to
replace these layouts with the finer one of them and have a way to strech
windows over multiple zones.

I think the following userinterface makes sense:
While previewing the snap (i.e. when the user presses Super, Shift and clicks
the mouse) 'select' the zone the cursor currently is over when another key
(let's say Shift) is pressed (or held). Color the selected zone in another
color. When the cursor is moved to another zone, the selected zone remains
highlighted. Then other zones can be selected the same way. When the user
releases the mouse button, the window is resized to the smallest rectangle
covering all the selected zones (maybe also draw the outline of this rectangle
in the preview).

### PR DESCRIPTION
**Pull request by domferr**
By holding the ALT key, windows are allowed to span on multiple zones. The zones selected are highlighted in green. The whole feature can be enabled/disabled in the settings. The following is an overview of the feature:

https://user-images.githubusercontent.com/14203981/236666596-b65867a2-688b-45ac-a0c4-6968b952efb8.mp4

- While grabbing, if you start pressing ALT you are allowed to span the window on multiple zones. If you stop holding ALT, the selection will reset (useful if you change your mind and you want to start the selection again).

The following is a playground I used for testing. It also shows the behaviour when the `Hold CTRL to snap windows` setting is enabled:

https://user-images.githubusercontent.com/14203981/236666712-4575e620-07c1-4132-bc90-17a4e275b905.mp4

The following is the behaviour when the `Hold CTRL to snap windows` setting is not enabled:

https://user-images.githubusercontent.com/14203981/236666893-8100fd63-531d-4a6d-a7be-53fc2975ac5c.mp4

Notes:
- It works with or without any margins set.
- I believe it doesn't make any sense to allow spanning a window in multiple zones when the  `Show tabs` setting is enabled. Because of that, if that setting is enabled, holding ALT key is ignored.
- Resolves #33 and it is less restrictive.
- If you select multiple zones on multiple monitors, the window will be moved on the first monitor found with a selection of zones.

Tested on Ubuntu 23.04, GNOME 44, with both Wayland and Xorg.

### CODE REVIEW

**Comment by meronz** [comment]
This is a big pr, I'll try to make time for reviewing it but I'm currently very busy so I cannot give you an estimate on that.

Thanks a lot for opening this and implementing such a useful feature!

**Comment by meronz** [comment]
I tested it and I must say, I like that you chose to implement it by holding a key instead of "dropping" the window in the line between two zones. I only have one minor pet peeve: we should make it evident that this feature is mutually-exclusive with the show-tabs option. I'd suggest two changes to achieve this:
- Disable one checkbox in `prefs_builder.ts` if the other one is active.
- Add a text description underneath the `SPAN_MULTIPLE_ZONES` checkbox, something along the lines of _"This feature does not work if you have the "Show tabs" feature enabled"_.

Do you think you can do that? 

Again, thanks for this very important feature!

**Review by meronz — APPROVED** [review]

**Comment by domferr** [comment]
> I tested it and I must say, I like that you chose to implement it by holding a key instead of "dropping" the window in the line between two zones. I only have one minor pet peeve: we should make it evident that this feature is mutually-exclusive with the show-tabs option. I'd suggest two changes to achieve this:
> 
>     * Disable one checkbox in `prefs_builder.ts` if the other one is active.
> 
>     * Add a text description underneath the `SPAN_MULTIPLE_ZONES` checkbox, something along the lines of _"This feature does not work if you have the "Show tabs" feature enabled"_.
> 
> 
> Do you think you can do that?
> 
> Again, thanks for this very important feature!

Sorry for the late reply. I agree with you that the changes you proposed are needed. I pushed them!
I added also the label "_This feature is not supported if you have the "Hold ALT to span multiple zones" feature enabled_" below the "Show tabs" checkbox otherwise it is not clear why the feature is disabled.

Let me know what you think about it!

**Comment by meronz** [comment]
I've tested it again, this is so awesome! Thanks again for the contribution!

**Comment by auipga** [comment]
Thank you so much!!

**Pull request merged**
